import * as Y from "yjs";
import { invoke } from "@tauri-apps/api/core";
import { PROTOCOL_VERSION } from "./protocol";
import "./style.css";

const APP_VERSION = "0.1.0";
const DEFAULT_SERVER = "http://localhost:8787";
type Settings = { color: string; opacity: number; fontFamily: string; fontSize: number; outline: string; background: string; x: number; y: number; visible: boolean; active: boolean; captureProtected: boolean };
const defaults: Settings = { color: "#ffffff", opacity: 1, fontFamily: "Arial", fontSize: 72, outline: "2px #000000", background: "transparent", x: 80, y: 80, visible: true, active: true, captureProtected: true };
const state = { settings: { ...defaults }, connected: false, socket: undefined as WebSocket | undefined, doc: new Y.Doc(), text: undefined as Y.Text | undefined };
state.text = state.doc.getText("text");
const settingsMap = state.doc.getMap<any>("settings");

const app = document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML = `<div id="overlay" class="overlay"><span id="overlay-text"></span></div><section class="panel"><div class="panel-head"><div><span class="eyebrow">TEXT ON SCREEN</span><h1>Настройки трансляции</h1></div><button id="hide-panel" class="icon">−</button></div><div class="grid"><label>Сервер<input id="server" value="${DEFAULT_SERVER}" /></label><label>WebSocket URL / код комнаты<input id="room-input" placeholder="wss://…?token=…" /></label></div><div class="actions"><button id="connect">Подключить</button><span id="connection" class="muted">Нет соединения</span></div><label>Текст<textarea id="local-text" placeholder="Введите текст или подключитесь к редактору"></textarea></label><div class="grid three"><label>Цвет<input id="color" type="color" value="#ffffff" /></label><label>Размер<input id="font-size" type="number" min="8" max="500" value="72" /></label><label>Прозрачность<input id="opacity" type="range" min="0" max="1" step="0.05" value="1" /></label></div><div class="grid"><label>Шрифт<input id="font-family" value="Arial" /></label><label>Фон<input id="background" value="transparent" /></label></div><div class="toggles"><label><input id="capture" type="checkbox" checked /> Не показывать в захвате</label><label><input id="active" type="checkbox" checked /> Активный режим</label></div><div class="actions"><button id="check-update" class="secondary">Проверить обновления</button><button id="install-update" hidden>Установить обновление</button><button id="reset" class="secondary">Сбросить (Ctrl+F8)</button></div><p id="update" class="muted"></p><p class="hint">F8 — видимость · F9 — активный режим · Ctrl+F8 — сброс · колесо — размер</p></section>`;
const $ = <T extends HTMLElement = HTMLInputElement>(selector: string) => document.querySelector<T>(selector)!;
const overlay = $("#overlay"), overlayText = $("#overlay-text"), panel = $(".panel"), localText = $("#local-text");
function render() { const s = state.settings; overlayText.textContent = state.text!.toString(); overlay.style.left = `${s.x}px`; overlay.style.top = `${s.y}px`; overlay.style.color = s.color; overlay.style.opacity = String(s.opacity); overlay.style.fontFamily = s.fontFamily; overlay.style.fontSize = `${s.fontSize}px`; overlay.style.textShadow = s.outline; overlay.style.background = s.background; overlay.classList.toggle("hidden", !s.visible); overlay.classList.toggle("inactive", !s.active); if (localText.value !== state.text!.toString()) localText.value = state.text!.toString(); $("#font-size").value = String(s.fontSize); $("#opacity").value = String(s.opacity); $("#color").value = s.color; $("#font-family").value = s.fontFamily; $("#background").value = s.background; $("#active").checked = s.active; $("#capture").checked = s.captureProtected; }
function applySettingsFromMap() { settingsMap.forEach((value, key) => { if (key in state.settings) (state.settings as any)[key] = value; }); render(); }
function setSetting<K extends keyof Settings>(key: K, value: Settings[K]) { state.doc.transact(() => settingsMap.set(key, value), "local"); state.settings[key] = value; render(); if (key === "captureProtected") void invoke("set_capture_protected", { protected: value }); if (key === "active") void invoke("set_click_through", { enabled: !value }); }
state.doc.on("update", (update, origin) => { if (origin !== "remote" && state.socket?.readyState === WebSocket.OPEN) state.socket.send(JSON.stringify({ type: "sync", update: btoa(String.fromCharCode(...update)) })); });
state.text.observe(render); settingsMap.observe(applySettingsFromMap); render();
localText.addEventListener("input", () => state.doc.transact(() => { state.text!.delete(0, state.text!.length); state.text!.insert(0, localText.value); }, "local"));
$("#color").addEventListener("input", e => setSetting("color", (e.target as HTMLInputElement).value)); $("#font-size").addEventListener("input", e => setSetting("fontSize", Number((e.target as HTMLInputElement).value))); $("#opacity").addEventListener("input", e => setSetting("opacity", Number((e.target as HTMLInputElement).value))); $("#font-family").addEventListener("input", e => setSetting("fontFamily", (e.target as HTMLInputElement).value)); $("#background").addEventListener("input", e => setSetting("background", (e.target as HTMLInputElement).value)); $("#capture").addEventListener("change", e => setSetting("captureProtected", (e.target as HTMLInputElement).checked)); $("#active").addEventListener("change", e => setSetting("active", (e.target as HTMLInputElement).checked));
$("#reset").addEventListener("click", () => { state.settings = { ...defaults }; Object.entries(defaults).forEach(([key, value]) => settingsMap.set(key, value)); render(); }); $("#hide-panel").addEventListener("click", () => panel.classList.toggle("collapsed"));
overlay.addEventListener("wheel", e => { if (!state.settings.active) return; e.preventDefault(); setSetting("fontSize", Math.max(8, Math.min(500, state.settings.fontSize + (e.deltaY < 0 ? 2 : -2)))); }, { passive: false });
let drag: { x: number; y: number; sx: number; sy: number } | undefined; overlay.addEventListener("pointerdown", e => { if (!state.settings.active) return; drag = { x: state.settings.x, y: state.settings.y, sx: e.clientX, sy: e.clientY }; overlay.setPointerCapture(e.pointerId); }); overlay.addEventListener("pointermove", e => { if (!drag) return; setSetting("x", drag.x + e.clientX - drag.sx); setSetting("y", drag.y + e.clientY - drag.sy); }); overlay.addEventListener("pointerup", () => { drag = undefined; });
function connect(url: string) { state.socket?.close(); const socket = new WebSocket(url); state.socket = socket; socket.onopen = () => { state.connected = true; $("#connection").textContent = "Подключено"; }; socket.onclose = () => { state.connected = false; $("#connection").textContent = "Соединение закрыто"; }; socket.onmessage = event => { const message = JSON.parse(event.data); if (message.type === "sync") Y.applyUpdate(state.doc, Uint8Array.from(atob(message.update), c => c.charCodeAt(0)), "remote"); }; }
let protocolBlocked = false;
$("#connect").addEventListener("click", () => { if (protocolBlocked) { $("#connection").textContent = "Нужно обновить приложение"; return; } const raw = $("#room-input").value.trim(); const url = raw.startsWith("ws") ? `${raw}${raw.includes("?") ? "&" : "?"}protocolVersion=${PROTOCOL_VERSION}` : `${$("#server").value.replace(/^http/, "ws")}/api/v1/sessions/${encodeURIComponent(raw)}?token=${encodeURIComponent(prompt("Токен просмотра") ?? "")}&protocolVersion=${PROTOCOL_VERSION}`; connect(url); });
window.addEventListener("keydown", e => { if (e.key === "F8") { e.preventDefault(); setSetting("visible", !state.settings.visible); } if (e.key === "F9") { e.preventDefault(); setSetting("active", !state.settings.active); } if (e.ctrlKey && e.key === "F8") { e.preventDefault(); $("#reset").click(); } });
function compareVersions(a: string, b: string) { const pa = a.split(".").map(Number), pb = b.split(".").map(Number); for (let i = 0; i < 3; i++) { if ((pa[i] ?? 0) !== (pb[i] ?? 0)) return (pa[i] ?? 0) - (pb[i] ?? 0); } return 0; }
let updateUrl = ""; async function checkUpdates() { const base = $("#server").value.replace(/\/$/, ""); $("#update").textContent = "Проверяем обновления…"; try { const versionResponse = await fetch(`${base}/api/v1/version`); const serverInfo = versionResponse.ok ? await versionResponse.json() : {}; protocolBlocked = Boolean(serverInfo.minimumClientVersion && compareVersions(APP_VERSION, serverInfo.minimumClientVersion) < 0); const response = await fetch(`${base}/api/v1/releases/latest`); if (!response.ok) throw new Error("Сервер релизов недоступен"); const release = await response.json(); if (release.version && compareVersions(release.version, APP_VERSION) > 0) { updateUrl = release.platforms?.["windows-x86_64"]?.url?.startsWith("http") ? release.platforms["windows-x86_64"].url : `${base}${release.platforms?.["windows-x86_64"]?.url ?? ""}`; $("#update").textContent = protocolBlocked ? `Требуется обновление до ${release.version}` : `Доступна версия ${release.version}`; $("#install-update").hidden = !updateUrl; } else $("#update").textContent = protocolBlocked ? `Нужно обновление до ${serverInfo.minimumClientVersion}` : `Установлена актуальная версия ${APP_VERSION}`; if (protocolBlocked) $("#connect").setAttribute("disabled", "true"); } catch (error) { $("#update").textContent = error instanceof Error ? error.message : "Ошибка проверки"; } }
$("#check-update").addEventListener("click", checkUpdates); $("#install-update").addEventListener("click", () => updateUrl && void invoke("open_release_url", { url: updateUrl })); void checkUpdates(); void invoke("set_capture_protected", { protected: true });

